### ISSUE TITLE
Failed to load the man package

### ISSUE THREAD

**Issue by maba** [kgrossjo/atom-man#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.197.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [man](https://github.com/kgrossjo/atom-man) package, v0.3.0

### Stack Trace

Failed to load the man package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/maba/Dropbox/Applicazioni/Atom/atom/packages/man/lib/man-view.coffee:4:199)
    at /Users/maba/Dropbox/Applicazioni/Atom/atom/packages/man/lib/man-view.coffee:11:5
    at Object.<anonymous> (/Users/maba/Dropbox/Applicazioni/Atom/atom/packages/man/lib/man-view.coffee:74:5)
    at Object.<anonymous> (/Users/maba/Dropbox/Applicazioni/Atom/atom/packages/man/lib/man-view.coffee:76:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/maba/Dropbox/Workspace/src",
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v1.1.0
atom-bourbon-snippets, v0.12.5
atom-runner, v2.3.0
autocomplete-plus, v2.12.1
color-picker, v1.7.0
emmet, v2.3.8
file-icons, v1.5.5
language-apache, v1.3.0
language-batch, v0.3.3
language-lua, v0.9.2
language-powershell, v2.0.1
linter, v0.12.1
linter-php, v0.0.12
man, v0.3.0
minimap, v4.8.0
project-manager, v1.15.5
redacted, v0.4.0
remote-atom, v1.2.6
remote-edit, v1.7.2
ssh-config, v0.10.1
terminal-status, v1.6.6
tool-bar, v0.1.0
tool-bar-main, v0.0.7
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by kgrossjo** [comment]
Thanks a lot for this report.  It really motivated me to work on Atom 1.0 compatibility.  Sorry for the long response time.  I think version 0.4.0 fixes it, could you please test?

**Comment by maba** [comment]
No problem. Now it works fine :)
Thanks for you work.
